workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "alpha"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCS9/ZjsWutfmru\n0PYA/P46vT9l8oXWdc1Ik5PvTwake2zDW1YmShjcueWVkYqWnCUEi+EN6OM+Lq8W\nk4K7H/4o3PuAm5CM0FQwomTmBmqMwQbBhjT2hKo2BOxKsFTAO00+fHZR+mbsGeas\nUbLJkVbEUfzkD/rp+NzZPslurGtl6N9rJLmQM8zeCIasLUbvg2H0133S5SOsDGWS\n/NaUfSf+b/r7Yucln48ayqkceJggmhrNLh1aIa3lXrtHZe0MKBeaFVpcAsceet4B\nRmeGhaDMFlLCsSiyfeKpDe1WeD0kZwnCTRmnlyeu65moyCbxpT5RvS/hiqSyNdO+\n3UEPUiKlAgMBAAECggEABI/u0Fvw14R8iHgooXxjs5+Ye6Saa9ShgClX9t5kD/rm\niVmeaZcJwV+s7+Zsyq2YsZTaXOPtRUrOM8bK+15BdckcWTrwXbVW3mFK0rWBcmfz\nOtKHdjKalQ2J50H6M4hzu/xBm7GzUbd2c27K0cUxpWuqdyBEM1CpdxNNo0z2Etuq\neWxI6GEPbnRsxGEN1hh4vOr7VB1ovYyeGvDt91TooWK3ztKGynnlPAmDwVJ0/Qlc\nDmZRDviNoYsDkcWjWaO4d7dXnUiMN7AEBk4cCVYV8HBaEPfa2CrJjWDB/+Uhr/oE\nARDmLa5qSH0KYZK5RkGDQigl7+HC7Lj7XdoXdO5PiQKBgQDD50wX0MheimENOL+K\n2S5Gt8cdm9Jf9NRQfJp0iFnMplI84S0q5LQMK08S2WxWz49MU0Q/RvyLTDWY5re+\njUzRWsO2VSlqQBQI5nGinA1IFE3bWCHWl24axV84HgCp0EbmNjpOcDl/CcnT/aXK\nkMg58uVagXCLk2ZyEnQS+8HevQKBgQDADbUVeVV0aCmPOVYn0yPU5oEKShYbWq+C\n7FSIKdRxO91Kee2OEmvuPSotWM0RbUTuMiQSPS5ELGvdanAb26lAjQD1yv6L+YVq\nPcko8LRbIGt8CtdSWsfBPcXAQ6kMsWVW/iTnehv88gSgWs6duyUeVYBLEaPb4gMk\nCRKDtupmCQKBgHcRqT08Z9yWbOCVYk4pLKhM4RgM8nPiIf19jn9PtIzfdlKMZmCQ\nuyI+XIRPZDrrUuSII432Pl8IBfeWG44U4eDJMvUqk86Bfeve7KhyAtyRgrTTv1Vn\nmsNovTQlgC+2aLFZulycd0XQlDxmCZOyJhCaom49CEO9ZmHk92nmXPJdAoGAMZMY\nPEvOsDa3C558S9lntWwuwQ4wuKznAz+n7mIF0ZjnXXMty++bZqrpOT1j6eyvz2Co\nCQE78SMaUNRJzhcckGoVZl0Y6d7l/m+mfmfr1l3/AMz3me2PBKXCZwfQGlOsWhFO\nS2Ys1VVPtmjaTsLhKPxfGoGaL4ce0m15FwDfbqkCgYEAptFn4GchJJy9c6OnASiG\nWMN+BhEwKs1sBEIX1RKAZyuljAmmGDXEiwSQ+GKjNBZiDoKbwjYgnRByp+e0B0cM\nVcokihV65AC/u9vmuAci1EDUCTg5MKotq7KGg1EB8Ns/bA7iV6xzVVBquj/jTPck\n3P6wlB6Li/5zslAqgb5yYFc=\n-----END PRIVATE KEY-----\n"

        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.flutteryaml
      vars:
        APP_ID: 1111111111 # <-- Put your APP ID here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#builds"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false

  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Flutter build webapp
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user_1@example.com
